/* Generated by scripts/generate_jaccard_policy_header.py. Do not edit. */
/* Source: config/policy_ngram.yaml; Pad::Auto-compatible ASCII preprocessing. */
#ifndef XDP_JACCARD_POLICY_GENERATED_H
#define XDP_JACCARD_POLICY_GENERATED_H

#define XDP_JACCARD_GENERATED_RULE_COUNT 2
#define XDP_JACCARD_GENERATED_KEYWORD_COUNT 13

#ifndef __BPF__
static const struct xdp_jaccard_policy_config xdp_jaccard_generated_config = {
  .keyword_count = 13, .rule_count = 2,
};
static const struct xdp_jaccard_rule xdp_jaccard_generated_rules[] = {
  {.threshold_milli = 800, .priority = 100, .route = XDP_ROUTE_CODING, .operator = XDP_JACCARD_OR, .arity = 3, .case_sensitive = 0, .keyword_count = 5},
  {.threshold_milli = 800, .priority = 90, .route = XDP_ROUTE_MATH, .operator = XDP_JACCARD_OR, .arity = 3, .case_sensitive = 0, .keyword_count = 8},
};
static const struct xdp_jaccard_keyword xdp_jaccard_generated_keywords[] = {
  {.count = 6, .total_grams = 6, .grams = {2105443, 2122607, 6516580, 7300197, 6579488, 6627360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 10, .total_grams = 10, .grams = {2105446, 2123381, 6714734, 7695971, 7234420, 6517865, 7629167, 6909806, 7302688, 7217184, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 7, .total_grams = 7, .grams = {2105444, 2122853, 6579554, 6644341, 6452583, 7694112, 6758432, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 11, .total_grams = 11, .grams = {2105441, 2122092, 6384743, 7104367, 6778738, 7303785, 7498100, 6911080, 7628909, 6843680, 7151648, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 10, .total_grams = 10, .grams = {2105458, 2126437, 7497062, 6645345, 6709603, 6382452, 6517871, 7630706, 7303712, 7479328, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 7, .total_grams = 7, .grams = {2105459, 2126703, 7565164, 7302262, 7108197, 7759136, 6627360, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 10, .total_grams = 10, .grams = {2105445, 2123121, 6648181, 7435617, 7692660, 6386793, 7629167, 6909806, 7302688, 7217184, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 12, .total_grams = 12, .grams = {2105444, 2122853, 6579570, 6648425, 7498102, 6911585, 7758196, 6386793, 7629174, 6911589, 7759136, 6627360, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 10, .total_grams = 10, .grams = {2105449, 2124142, 6909556, 7238757, 7628135, 6645618, 6779489, 7496044, 6384672, 7086112, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 8, .total_grams = 8, .grams = {2105453, 2125153, 7168372, 6386802, 7631465, 7498104, 6912032, 7872544, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 13, .total_grams = 13, .grams = {2105456, 2125938, 7369327, 7499618, 7299681, 6447458, 6382185, 6449516, 6909033, 7104884, 6911097, 7633184, 7938080, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, .rule_id = 1},
  {.count = 10, .total_grams = 10, .grams = {2105447, 2123621, 6776175, 6647661, 7302501, 7169396, 6648946, 7631481, 7502112, 7938080, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 11, .total_grams = 11, .grams = {2105443, 2122593, 6513004, 6384739, 7103349, 6518124, 7695457, 7102836, 6386789, 7628064, 6627360, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0}, .rule_id = 1},
};
#endif

#endif
