/* Generated by generate_policy_modules.py. Do not edit. */
/* Source: config/policy_ngram.yaml */
#ifndef XDP_KEYWORD_MODULES_GENERATED_H
#define XDP_KEYWORD_MODULES_GENERATED_H
#define XDP_KEYWORD_ENABLE_NGRAM 1
#define XDP_KEYWORD_ENABLE_BM25 0
#endif
