/* Generated by generate_bm25_policy_header.py. Do not edit. */
/* Source: config/policy_bm25.yaml; bm25 crate 2.3 defaults, Q1e6 scores. */
#ifndef XDP_BM25_POLICY_GENERATED_H
#define XDP_BM25_POLICY_GENERATED_H

#define XDP_BM25_GENERATED_RULE_COUNT 4
#define XDP_BM25_GENERATED_DOCUMENT_COUNT 16
#define XDP_BM25_GENERATED_TERM_COUNT 16

#ifndef __BPF__
static const struct xdp_bm25_policy_config xdp_bm25_generated_config = {
  .rule_count = 4, .document_count = 16,
  .thresholds_micro = {100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, },
};
static const struct xdp_bm25_rule xdp_bm25_generated_rules[] = {
  {.threshold_micro = 100000, .priority = 100, .route = XDP_ROUTE_CODING, .operator = XDP_BM25_OR, .document_start = 0, .document_count = 4, .document_mask = 15},
  {.threshold_micro = 100000, .priority = 90, .route = XDP_ROUTE_MATH, .operator = XDP_BM25_OR, .document_start = 4, .document_count = 4, .document_mask = 240},
  {.threshold_micro = 100000, .priority = 80, .route = XDP_ROUTE_QA, .operator = XDP_BM25_OR, .document_start = 8, .document_count = 4, .document_mask = 3840},
  {.threshold_micro = 100000, .priority = 70, .route = XDP_ROUTE_WRITING, .operator = XDP_BM25_OR, .document_start = 12, .document_count = 4, .document_mask = 61440},
};
struct xdp_bm25_generated_term { __u32 hash; struct xdp_bm25_term_weights value; };
static const struct xdp_bm25_generated_term xdp_bm25_generated_terms[] = {
  {.hash = 11041011U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973}}},
  {.hash = 114665541U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 231289696U, .value = {.weights = {0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 309439324U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0}}},
  {.hash = 1032087243U, .value = {.weights = {0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 1394468022U, .value = {.weights = {0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 1788839250U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0}}},
  {.hash = 2172135276U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0}}},
  {.hash = 2222987743U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0}}},
  {.hash = 2486886355U, .value = {.weights = {0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 2604767279U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 2664841801U, .value = {.weights = {0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 2724541488U, .value = {.weights = {0, 0, 0, 0, 1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
  {.hash = 3044443532U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0}}},
  {.hash = 3190202204U, .value = {.weights = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1203973, 0, 0, 0}}},
  {.hash = 4180765940U, .value = {.weights = {1203973, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}},
};
#endif

#endif
