/* Generated by benchmarks/policy/generate_jaccard_policy_header.py. Do not edit. */
/* Source: config/policy_ngram.yaml; Pad::Auto-compatible ASCII preprocessing. */
#ifndef XDP_JACCARD_POLICY_GENERATED_H
#define XDP_JACCARD_POLICY_GENERATED_H

#define XDP_JACCARD_GENERATED_RULE_COUNT 4
#define XDP_JACCARD_GENERATED_KEYWORD_COUNT 16

#ifndef __BPF__
static const struct xdp_jaccard_policy_config xdp_jaccard_generated_config = {
  .keyword_count = 16, .rule_count = 4,
};
static const struct xdp_jaccard_rule xdp_jaccard_generated_rules[] = {
  {.threshold_milli = 800, .priority = 100, .route = XDP_ROUTE_CODING, .operator = XDP_JACCARD_OR, .arity = 3, .case_sensitive = 0, .keyword_count = 4},
  {.threshold_milli = 800, .priority = 90, .route = XDP_ROUTE_MATH, .operator = XDP_JACCARD_OR, .arity = 3, .case_sensitive = 0, .keyword_count = 4},
  {.threshold_milli = 800, .priority = 80, .route = XDP_ROUTE_QA, .operator = XDP_JACCARD_OR, .arity = 3, .case_sensitive = 0, .keyword_count = 4},
  {.threshold_milli = 800, .priority = 70, .route = XDP_ROUTE_WRITING, .operator = XDP_JACCARD_OR, .arity = 3, .case_sensitive = 0, .keyword_count = 4},
};
static const struct xdp_jaccard_keyword xdp_jaccard_generated_keywords[] = {
  {.count = 6, .total_grams = 6, .grams = {2105443, 2122607, 6516580, 7300197, 6579488, 6627360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 10, .total_grams = 10, .grams = {2105446, 2123381, 6714734, 7695971, 7234420, 6517865, 7629167, 6909806, 7302688, 7217184, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 9, .total_grams = 9, .grams = {2105456, 2125938, 7369327, 7499623, 7300978, 6779489, 7496045, 6384928, 7151648, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 11, .total_grams = 11, .grams = {2105449, 2124141, 6909296, 7172204, 7367781, 7103853, 6647141, 7169390, 6647412, 7238688, 7610400, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0}, .rule_id = 0},
  {.count = 7, .total_grams = 7, .grams = {2105459, 2126703, 7565164, 7302262, 7108197, 7759136, 6627360, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 10, .total_grams = 10, .grams = {2105445, 2123121, 6648181, 7435617, 7692660, 6386793, 7629167, 6909806, 7302688, 7217184, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 12, .total_grams = 12, .grams = {2105444, 2122853, 6579570, 6648425, 7498102, 6911585, 7758196, 6386793, 7629174, 6911589, 7759136, 6627360, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 11, .total_grams = 11, .grams = {2105443, 2122593, 6513004, 6384739, 7103349, 6518124, 7695457, 7102836, 6386789, 7628064, 6627360, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0}, .rule_id = 1},
  {.count = 10, .total_grams = 10, .grams = {2105457, 2126197, 7435621, 7693683, 6648692, 7566441, 7629167, 6909806, 7302688, 7217184, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, .rule_id = 2},
  {.count = 8, .total_grams = 8, .grams = {2105441, 2122094, 6385267, 7238519, 7567205, 7824754, 6648352, 7479328, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 2},
  {.count = 9, .total_grams = 9, .grams = {2105445, 2123128, 6649968, 7893100, 7367777, 7102825, 6383982, 6909472, 7217184, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 2},
  {.count = 8, .total_grams = 8, .grams = {2105444, 2122853, 6579558, 6645353, 6711662, 6909541, 7234848, 6627360, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 2},
  {.count = 7, .total_grams = 7, .grams = {2105463, 2127730, 7828073, 7498100, 6911077, 7628064, 6627360, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 3},
  {.count = 7, .total_grams = 7, .grams = {2105445, 2123123, 6648691, 7566177, 7561593, 6388000, 7938080, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 3},
  {.count = 7, .total_grams = 7, .grams = {2105444, 2122866, 6582881, 7496038, 6383220, 6714400, 7610400, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 3},
  {.count = 9, .total_grams = 9, .grams = {2105443, 2122607, 6516589, 7302512, 7172207, 7368563, 7304037, 7562528, 6627360, 0, 0, 0, 0, 0, 0, 0}, .gram_counts = {1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, .rule_id = 3},
};
#endif

#endif
