#!/usr/bin/env python3
"""Generate a C header from the hashed n-gram routing model JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


EXPECTED_CLASSES = ["coding", "general", "math"]


def c_array(values: list[int]) -> str:
    return ", ".join(str(int(value)) for value in values)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("model", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    with args.model.open() as file:
        model = json.load(file)

    classes = model.get("classes")
    if classes != EXPECTED_CLASSES:
        raise ValueError(f"expected classes {EXPECTED_CLASSES}, got {classes!r}")

    ngram_range = model.get("ngram_range")
    if ngram_range != [3, 3]:
        raise ValueError(f"expected 3-gram model, got ngram_range={ngram_range!r}")

    n_features = int(model.get("n_features", 0))
    if n_features <= 0 or n_features & (n_features - 1) != 0:
        raise ValueError("n_features must be a positive power of two")

    weights = model.get("weights")
    if not isinstance(weights, list) or len(weights) != 3:
        raise ValueError("weights must be a 3-row array")
    if any(not isinstance(row, list) or len(row) != n_features for row in weights):
        raise ValueError("each weight row must have n_features entries")

    bias = model.get("bias")
    if not isinstance(bias, list) or len(bias) != 3:
        raise ValueError("bias must have three entries")

    for value in list(bias) + [item for row in weights for item in row]:
        if int(value) < -32768 or int(value) > 32767:
            raise ValueError(f"model value {value!r} does not fit in int16")

    rows = []
    for index in range(n_features):
        rows.append(
            "  {"
            f"{int(weights[0][index])}, "
            f"{int(weights[1][index])}, "
            f"{int(weights[2][index])}"
            "},"
        )

    lines = [
        "/* Generated by scripts/generate_ngram_header.py. Do not edit by hand. */",
        f"/* Source: {args.model.as_posix()} */",
        "#ifndef XDP_NGRAM_MODEL_GENERATED_H",
        "#define XDP_NGRAM_MODEL_GENERATED_H",
        "",
        f"#define XDP_NGRAM_FEATURES {n_features}",
        f"#define XDP_NGRAM_BIAS_CODING {int(bias[0])}",
        f"#define XDP_NGRAM_BIAS_GENERAL {int(bias[1])}",
        f"#define XDP_NGRAM_BIAS_MATH {int(bias[2])}",
        "",
        "#ifndef __BPF__",
        "static const struct xdp_ngram_weight xdp_ngram_model[XDP_NGRAM_FEATURES] = {",
        *rows,
        "};",
        "#endif",
        "",
        "#endif",
        "",
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
